services:
  chrome_scraper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DRIVER_EXECUTABLE_PATH=/usr/lib/chromium/chromedriver
    volumes:
      - ./src/scraping_service:/app/src/scraping_service # This removes the need to rebuild the image every time the code changes
