services:
  chrome_scraper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DRIVER_EXECUTABLE_PATH=/usr/lib/chromium/chromedriver
