networks:
  web:
    external: true

services:
  scraping_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CONCURRENCY_LIMIT=5
    networks:
      - web
    labels:
      traefik.enable: "true"
      traefik.http.routers.adguard.rule: Host(`scraper.kiwisaki.com`)
      traefik.http.routers.adguard.entrypoints: websecure
      traefik.http.routers.adguard.tls.certresolver: myresolver
      traefik.http.services.adguard.loadbalancer.server.port: 8000