name: Deploy to Desktop with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH key for authentication
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Deployment on Desktop
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "GITHUB_REPOSITORY='${{ github.repository }}' bash -s" << 'EOF'
            set -e

            REPO_NAME=$(basename "${GITHUB_REPOSITORY}")

            cd /home/${{ secrets.SSH_USER }}/Desktop

            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            if [ ! -d "$REPO_NAME" ]; then
              echo "Cloning repository via SSH..."
              git clone git@github.com:${GITHUB_REPOSITORY}.git "$REPO_NAME"
            fi

            cd "$REPO_NAME"

            git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git

            if [ ! -d ".git" ]; then
              echo "Not a Git repository. Aborting."
              exit 1
            fi

            echo "Pulling latest changes"
            git pull origin main

            echo "Creating .env file from GitHub secret"
            echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

            echo "Updating Docker services"
            docker compose pull
            docker compose up -d --remove-orphans

            echo "Cleaning up unused Docker images"
            docker system prune -f
          EOF